name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test Day 1
      run: cd day1 && go test -v ./... && cd ..

    - name: Test Day 2
      run: cd day2 && go test -v ./... && cd ..
